fragment TypeRef on __Type {
    name
    kind
    ofType {
      name
      kind
      ofType {
        name
        kind
        ofType {
          name
          kind
        }
      }
    }
}

{
  __schema {
    types {
      name
      kind
      fields {
        name
        type {
          ...TypeRef
        }
        args {
          name
          type {
            ...TypeRef
          }
          defaultValue
        }
      }
    }
  }
}
